name: grmpy

dependencies:
  - python=3.7
  - numpy
  - pandas
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - numba
  - matplotlib
  - flake8
  - seaborn
  - pandoc
  - pip
  - pip:
    - sphinxcontrib.bibtex # <2.0.0
    - sphinx_rtd_theme
    - linearmodels
    - oyaml
    - isort
    - nbsphinx
    - sphinx_rtd_theme
    - pytest-cov
    - jupyterlab
    - scikit-misc
    - scikit-learn
