name: grmpy

channels:
  - defaults
  - conda-forge

dependencies:
  - python>=3.7
  - pip
  - isort
  - jupyterlab
  - linearmodels
  - matplotlib
  - nbsphinx
  - numba
  - numpy>=1.2
  - flake8
  - oyaml
  - pandas>=0.24
  - pandoc
  - pytest>=6.2.1
  - pytest-cov
  - pytest-xdist
  - scipy
  - seaborn
  - sphinxcontrib-bibtex<2.0.0
  - sphinx_rtd_theme
  - statsmodels
  - tox-conda
  - pip:
    - kernreg
    - scikit-misc
    - scikit-learn
