name: grmpy

dependencies:
  - python=3.6
  - numpy
  - pandas
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - matplotlib
  - linearmodels
  - pip:
    - sphinxcontrib.bibtex
    - sphinx_rtd_theme
