name: grmpy

channels:
  - defaults
  - conda-forge

dependencies:
  - python>=3.7
  - pip
  - isort
  - jupyterlab
  - linearmodels
  - matplotlib>=3.3.3
  - nbsphinx
  - numpy>=1.19.5
  - flake8
  - oyaml
  - pandas>=1.2.0
  - pandoc
  - pytest>=6.2.1
  - pytest-cov
  - pytest-xdist
  - scipy
  - seaborn
  - sphinxcontrib-bibtex<2.0.0
  - sphinx_rtd_theme
  - statsmodels
  - tox-conda
  - pip:
    - kernreg
    - scikit-misc==0.1.3
    - scikit-learn
