name: grmpy

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.7,<3.9
  - numpy
  - pandas
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - numba
  - matplotlib
  - flake8
  - scikit-learn
  - seaborn
  - pandoc
  - pip
  - pip:
    - sphinxcontrib.bibtex
    - sphinx_rtd_theme
    - linearmodels
    - oyaml
    - isort
    - nbsphinx
    - sphinx_rtd_theme
    - pytest-cov
    - jupyterlab
    - scikit-misc
