name: grmpy

dependencies:
  - python=3.6
  - numpy
  - pandas
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - matplotlib
  - flake8
  - seaborn
  - pandoc
  - pip:
    - sphinxcontrib.bibtex
    - sphinx_rtd_theme
    - linearmodels
    - oyaml
    - grmpy
    - isort
    - nbsphinx
    - sphinx_rtd_theme
    - pytest-cov
    - jupyter


