#! python


def build(ctx):

        # Illustrate use of run_py_script with automatic model specification.
        ctx(
            features='run_py_script',
            source='fig-eh-marginal-effect.py',
            deps=[
                ctx.path_to(ctx, 'IN_SIMULATE', 'simulate_auxiliary.py'),
                ctx.path_to(ctx, 'IN_READ', 'read.py'),
		ctx.path_to(ctx, 'IN_READ', 'read_auxiliary.py'),
                ctx.path_to(ctx, 'IN_CHECK', 'check.py'),
		ctx.path_to(ctx, 'IN_CHECK', 'auxiliary.py'),
		ctx.path_to(ctx, 'IN_CHECK', 'custom_exceptions.py'),
		ctx.path_to(ctx, 'IN_FIGURES', 'tutorial.grmpy.ini'),
            ] ,
            target=[
                ctx.path_to(ctx, 'OUT_FIGURES', 'fig-eh-marginal-effect.png'),
		ctx.path_to(ctx, 'OUT_DATA', 'X.csv') 
            ] 
        )

	# Illustrate use of run_py_script with automatic model specification.
        ctx(
            features='run_py_script',
            source='fig-local-average-treatment.py',
            deps=[
                ctx.path_to(ctx, 'IN_SIMULATE', 'simulate_auxiliary.py'),
                ctx.path_to(ctx, 'IN_READ', 'read.py'),
		ctx.path_to(ctx, 'IN_READ', 'read_auxiliary.py'),
                ctx.path_to(ctx, 'IN_CHECK', 'check.py'),
		ctx.path_to(ctx, 'IN_CHECK', 'auxiliary.py'),
		ctx.path_to(ctx, 'IN_CHECK', 'custom_exceptions.py'),
		ctx.path_to(ctx, 'IN_FIGURES', 'tutorial.grmpy.ini'),
		ctx.path_to(ctx, 'OUT_DATA', 'X.csv') 
            ] ,
            target=[
                ctx.path_to(ctx, 'OUT_FIGURES', 'fig-local-average-treatment.png'),
	
            ] 
        )

