name: grmpy_tutorial

dependencies:
  - python=3.6
  - numpy
  - pandas
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - sphinx_rtd_theme
  - matplotlib
  - seaborn
  - numba
  - json
  - pip
  - scikit-misc
  - sklearn
