name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # auto-update-conda: true
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
         # shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
        # run: pip install tox
      - name: Run Tox
        # shell: bash -l {0}
        run: tox -e py