name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8']

    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        shell: bash -l {0}
        run: conda install -c conda-forge tox-conda
      - name: Run Tox
        shell: bash -l {0}
        run: tox